config:
  backup: true
  banner: true
  create: true
  dotpath: src
  ignoreempty: false
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  d_um:
    dst: ~/.um
    src: um
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore_global:
    dst: ~/.gitignore_global
    src: gitignore_global
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_zsh_history:
    dst: ~/.zsh_history
    src: zsh_history
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
profiles:
  abnb.zt.andyfang.biz:
    dotfiles:
    - f_zshrc
    - f_gitignore_global
    - f_gitconfig
    - d_um
    - f_zsh_history
    - f_tmux.conf
  asus-linux:
    dotfiles:
    - f_zshrc
    - f_gitignore_global
    - f_gitconfig
    - d_um
    - f_zsh_history
