config:
  backup: true
  banner: true
  create: true
  dotpath: src
  ignoreempty: false
  keepdot: false
  link_dotfile_default: link
  link_on_import: link
  longkey: false
  showdiff: true
  workdir: ~/.config/dotdrop
dotfiles:
  f_nvim:
    dst: ~/.config/nvim/init.vim
    src: nvim/init.vim
  d_um:
    dst: ~/.um
    src: um
  f_gitconfig:
    dst: ~/.gitconfig
    src: gitconfig
  f_gitignore_global:
    dst: ~/.gitignore_global
    src: gitignore_global
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
  f_zsh_history:
    dst: ~/.zsh_history
    src: zsh_history
    link: nolink
  f_zshrc:
    dst: ~/.zshrc
    src: zshrc
  d_ssh_config.d:
    src: ssh/config.d
    dst: ~/.ssh/config.d
  f_ssh_config:
    src: ssh/config
    dst: ~/.ssh/config
  f_ssh_platform.d_macos:
    src: ssh/platform.d/macos
    dst: ~/.ssh/platform.d/macos
  f_local.config.zsh:
    src: dotfiles/local.config.zsh
    dst: ~/dotfiles/local.config.zsh
profiles:
  baseline:
    dotfiles:
    - f_nvim
    - f_zshrc
    - f_gitignore_global
    - f_gitconfig
    - d_um
    - f_zsh_history
    - f_tmux.conf
    - d_ssh_config.d
    - f_ssh_config
    - f_local.config.zsh

  andys-mbp14:
    dotfiles:
      - f_ssh_platform.d_macos
    include:
      - baseline
  dell-server:
    include:
      - baseline
